// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUPsdXewBfnOqVjIVMbeeKArkLvLa9h30',
    appId: '1:455669201430:web:3c01c375a5d15b9c75d337',
    messagingSenderId: '455669201430',
    projectId: 'strolls-ff2c8',
    authDomain: 'strolls-ff2c8.firebaseapp.com',
    storageBucket: 'strolls-ff2c8.appspot.com',
    measurementId: 'G-PNNFJ3RJCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRzoRW9BnhjhOmiqPkigsIBt3VVKhTyZ8',
    appId: '1:455669201430:android:378f3117ee4e7f8e75d337',
    messagingSenderId: '455669201430',
    projectId: 'strolls-ff2c8',
    storageBucket: 'strolls-ff2c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL4GyuY9l8vsFJx52uX7cLymWoDdIrCA0',
    appId: '1:455669201430:ios:016727d5ef020ec975d337',
    messagingSenderId: '455669201430',
    projectId: 'strolls-ff2c8',
    storageBucket: 'strolls-ff2c8.appspot.com',
    iosClientId: '455669201430-b7aet33u5m30hif7iufl15t859b234e5.apps.googleusercontent.com',
    iosBundleId: 'com.example.strolls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL4GyuY9l8vsFJx52uX7cLymWoDdIrCA0',
    appId: '1:455669201430:ios:77a8867b45659b8775d337',
    messagingSenderId: '455669201430',
    projectId: 'strolls-ff2c8',
    storageBucket: 'strolls-ff2c8.appspot.com',
    iosClientId: '455669201430-oikoj6chtg3s82lbuckmci2fom7c7ngs.apps.googleusercontent.com',
    iosBundleId: 'com.example.strolls.RunnerTests',
  );
}
